[package]
name = "hello-rust"
version = "0.1.0"
authors = ["WuQiang <wuqiang01_cd@keruyun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
rand = "0.5.5"
